# Generated by Django 4.2.7 on 2023-12-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_moneytransfermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransfermodel',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
