# Generated by Django 4.2.7 on 2023-12-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_moneytransfermodel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransfermodel',
            name='receiver',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
