# Generated by Django 4.2.7 on 2023-12-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_moneytransfermodel_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransfermodel',
            name='balance_after_transaction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
