# Generated by Django 4.2.7 on 2023-12-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_moneytransfermodel_balance_after_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransfermodel',
            name='receiver',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
